<?php
/**
 * Base Database Response.
 *
 * @package ChurchRoster\Db
 * @author  Caspar Green
 * @since   ver 1.0.0
 */

namespace ChurchRoster\Db;

use PDOStatement;

/**
 * Base Database Response class.
 *
 * @package ChurchRoster\Db
 * @author  Caspar Green
 * @since   ver 1.0.0
 */
class DBResponseBase implements DBResponse
{
    /**
     * PDO Statement generated by the query.
     * @var PDOStatement|null
     */
    private $statement;

    /**
     * Whether the response is an error.
     * @var bool
     */
    private $isError;

    /**
     * Response message (usually regarding an error).
     * @var string
     */
    private $message;

    /**
     * Data, if any, returned from the query.
     * @var array
     */
    private $content;

    /**
     * DBResponseBase constructor.
     *
     * @param bool $isError Whether the query resulted in an error.
     * @param string $message A message (usually about an error).
     * @param PDOStatement|null $statement The PDO Statement generated by the query.
     * @param array $content Content, if any, returned from the query.
     */
    public function __construct(
        PDOStatement $statement,
        bool $isError = false,
        string $message = '',
        array $content = []
    ) {
        $this->statement = $statement;
        $this->isError = $isError;
        $this->message = $message;
        $this->content = $content;
    }

    /**
     * Is the database response an error.
     *
     * @return bool
     * @since  ver 1.0.0
     *
     * @author Caspar Green
     */
    public function isError(): bool
    {
        return $this->isError;
    }

    /**
     * Get the response message.
     *
     * @return string
     * @since  ver 1.0.0
     *
     * @author Caspar Green
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * Get the PDO Statement.
     *
     * @return PDOStatement
     * @since  ver 1.0.0
     *
     * @author Caspar Green
     */
    public function getStatement(): PDOStatement
    {
        return $this->statement;
    }

    /**
     * Get the response content.
     *
     * @return array
     * @since  ver 1.0.0
     *
     * @author Caspar Green
     */
    public function getResponseContent(): array
    {
        return $this->content;
    }
}
